server:
  port: ${SERVER_PORT:8080}

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user-service/**
              filters:
                - name: RewritePath
                  args:
                    regexp: ^/user-service(?<remaining>/.*)$
                    replacement: ${remaining}
                - name: CircuitBreaker
                  args:
                    name: serviceCircuitBreaker
                    fallbackUri: forward:/fallback
                - name: AddRequestHeader
                  args:
                    name: X-Service
                    value: user-service

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/product-service/**
              filters:
                - name: RewritePath
                  args:
                    regexp: ^/product-service(?<remaining>/.*)$
                    replacement: ${remaining}
                - name: CircuitBreaker
                  args:
                    name: serviceCircuitBreaker
                    fallbackUri: forward:/fallback
                - name: AddRequestHeader
                  args:
                    name: X-Service
                    value: product-service


            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/order-service/**
              filters:
                - name: RewritePath
                  args:
                    regexp: ^/order-service(?<remaining>/.*)$
                    replacement: ${remaining}
                - name: CircuitBreaker
                  args:
                    name: serviceCircuitBreaker
                    fallbackUri: forward:/fallback
                - name: AddRequestHeader
                  args:
                    name: X-Service
                    value: order-service

            - id: moderation-service
              uri: lb://moderation-service
              predicates:
                - Path=/moderation-service/**
              filters:
                - name: RewritePath
                  args:
                    regexp: ^/moderation-service(?<remaining>/.*)$
                    replacement: ${remaining}
                - name: CircuitBreaker
                  args:
                    name: serviceCircuitBreaker
                    fallbackUri: forward:/fallback
                - name: AddRequestHeader
                  args:
                    name: X-Service
                    value: moderation-service

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        record-exceptions:
          - java.net.SocketException
          - java.net.SocketTimeoutException
          - org.springframework.web.client.ResourceAccessException

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    ru.itmo.gateway: DEBUG

springdoc:
  api-docs:
    enabled: true   
    path: /v3/api-docs  

  swagger-ui:
    enabled: true               
    path: /swagger-ui.html
    urls:                      
      - name: "API Gateway"
        url: /v1/api-docs

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,gateway,prometheus


eureka:
  instance:
    hostname: gateway-service
    instance-id: gateway-service:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:eureka}:${EUREKA_PORT:8761}/eureka
    register-with-eureka: true
    fetch-registry: true
