server:
  port: ${SERVER_PORT:8084}
  servlet:
    context-path: /

spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:postgres-moderation}:${DB_PORT:5432}/${DB_NAME:itmomarket_moderation}
    username: ${DB_USER:itmouser}
    password: ${DB_PASSWORD:itmopassword}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 300s
      validation-query: SELECT 1
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true

logging:
  level:
    ru.itmo.market: DEBUG

app:
  moderation:
    batch-size: 10
    timeout: 30

eureka:
  instance:
    hostname: moderation-service
    instance-id: moderation-service:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:eureka}:${EUREKA_PORT:8761}/eureka
    register-with-eureka: true
    fetch-registry: true

# Feign Client settings
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  circuitbreaker:
    enabled: true

# Resilience4j for Moderation Service
resilience4j:
  circuitbreaker:
    instances:
      product-service:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
      user-service:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
  timelimiter:
    instances:
      product-service:
        timeoutDuration: 10s
      user-service:
        timeoutDuration: 10s
