server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-product}:${DB_PORT:5432}/${DB_NAME:itmomarket_product}
    username: ${DB_USER:itmouser}
    password: ${DB_PASSWORD:itmopassword}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 20
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true

logging:
  level:
    ru.itmo.market.repository: DEBUG

app:
  cache:
    ttl: 3600
    max-size: 1000

eureka:
  instance:
    hostname: product-service
    instance-id: product-service:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:eureka}:${EUREKA_PORT:8761}/eureka
    register-with-eureka: true
    fetch-registry: true
