server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:postgres-user}:${DB_PORT:5432}/${DB_NAME:itmomarket_user}
    username: ${DB_USER:itmouser}
    password: ${DB_PASSWORD:itmopassword}
    pool:
      initial-size: 10
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true

logging:
  level:
    ru.itmo.user.service: DEBUG
    org.springframework.security: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v1/api-docs

app:
  jwt:
    secret: ${JWT_SECRET:your-secret-key-min-32-chars-long-here}
    expiration: 86400000

eureka:
  instance:
    hostname: user-service
    instance-id: user-service:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:eureka}:${EUREKA_PORT:8761}/eureka
    register-with-eureka: true
    fetch-registry: true
